


SELECT DISTINCT (DATENAME(dw, FECHA_ARQUEO)) as DÍA, (DATEPART(day,FECHA_ARQUEO)) as DÍA_NÚMERO, BONO_COND AS PORCENTAJE 
FROM ARQUEO
where FECHA_ARQUEO between '02-05-2017' and '15-05-2017'
ORDER BY (DATEPART(day,FECHA_ARQUEO))


